[2023-12-10 22:49:25,843] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline.data_create manual__2023-12-10T17:49:23.219548+00:00 [queued]>
[2023-12-10 22:49:25,849] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline.data_create manual__2023-12-10T17:49:23.219548+00:00 [queued]>
[2023-12-10 22:49:25,849] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 22:49:25,849] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-12-10 22:49:25,849] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 22:49:25,865] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): data_create> on 2023-12-10 17:49:23.219548+00:00
[2023-12-10 22:49:25,868] {standard_task_runner.py:52} INFO - Started process 26524 to run task
[2023-12-10 22:49:25,884] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline', 'data_create', 'manual__2023-12-10T17:49:23.219548+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/final_script.py', '--cfg-path', '/tmp/tmpxqld_q8o', '--error-file', '/tmp/tmphvmr_044']
[2023-12-10 22:49:25,884] {standard_task_runner.py:80} INFO - Job 39: Subtask data_create
[2023-12-10 22:49:25,924] {task_command.py:369} INFO - Running <TaskInstance: pipeline.data_create manual__2023-12-10T17:49:23.219548+00:00 [running]> on host vmac-VirtualBox
[2023-12-10 22:49:25,987] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=pipeline
AIRFLOW_CTX_TASK_ID=data_create
AIRFLOW_CTX_EXECUTION_DATE=2023-12-10T17:49:23.219548+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-10T17:49:23.219548+00:00
[2023-12-10 22:49:25,988] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 22:49:25,988] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/vmac/lab3/scripts/data_create.py']
[2023-12-10 22:49:25,997] {subprocess.py:85} INFO - Output:
[2023-12-10 22:49:27,602] {subprocess.py:92} INFO - Downloading...
[2023-12-10 22:49:27,606] {subprocess.py:92} INFO - From: https://drive.google.com/uc?id=1d23lf2o2-kYa631W_byvQv1Xu6sQ8Bgw
[2023-12-10 22:49:27,606] {subprocess.py:92} INFO - To: /home/vmac/lab3/dataset/dataset.csv
[2023-12-10 22:49:28,386] {subprocess.py:92} INFO -   0%|          | 0.00/3.95M [00:00<?, ?B/s] 13%|█▎        | 524k/3.95M [00:00<00:01, 2.81MB/s] 27%|██▋       | 1.05M/3.95M [00:00<00:00, 3.68MB/s] 53%|█████▎    | 2.10M/3.95M [00:00<00:00, 4.54MB/s] 80%|███████▉  | 3.15M/3.95M [00:00<00:00, 5.41MB/s]100%|██████████| 3.95M/3.95M [00:00<00:00, 5.72MB/s]100%|██████████| 3.95M/3.95M [00:00<00:00, 5.10MB/s]
[2023-12-10 22:49:28,478] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 22:49:28,562] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=data_create, execution_date=20231210T174923, start_date=20231210T174925, end_date=20231210T174928
[2023-12-10 22:49:28,594] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-10 22:49:28,674] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
